name: Deploy Service Demo

on:
  push:
    branches: [ "main" ]

jobs:
  # 纯净调用，不传递任何敏感信息
  call-standard-pipeline:
    uses: zentrix566/my-devops-core/.github/workflows/java-standard-ci.yml@main
    with:
      service_name: "test-app-service"
      java_version: "17"