name: Deploy Service

on:
  push:
    branches: [ "main" ]

jobs:
  call-workflow:
    # 引用中央仓库的定义
    uses: zentrix566/my-devops-core/.github/workflows/java-standard-ci.yml@v1
    with:
      service_name: "order-service"
      java_version: "17"
    secrets:
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}